#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout
    methods: GET

connect_facebook_check:
    path: /connect_facebook_check
    methods: [GET, POST]

connect_google_check:
    path: /connect_google_check
    methods: [GET, POST]
